 platform :ios, '9.0'

target 'WhatWeSee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhatWeSee
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SDWebImage'

end
